cross_over_app_user_homepage:
    path:     /
    defaults: { _controller: CrossOverAppUserBundle:Registration:registration }

registration:
    pattern:  /register
    defaults: { _controller: CrossOverAppUserBundle:Registration:registration }

registration_user_create:
    pattern:  /registration/user/create
    defaults: { _controller: CrossOverAppUserBundle:Registration:registrationCreate }



    
news_site_index:
    pattern:  /news/index
    defaults: { _controller: CrossOverAppUserBundle:News:index}    

news_article_delete:
    pattern:  /news/{id}/delete
    defaults: { _controller: CrossOverAppUserBundle:News:delete} 
    
cross_over_news_new:   
    pattern:  /news/new
    defaults: { _controller: CrossOverAppUserBundle:News:new} 

cross_over_news_create:   
    pattern:  /news/create
    defaults: { _controller: CrossOverAppUserBundle:News:createNew}    

news_site_show:
    pattern:  /news/{id}/show
    defaults: { _controller: CrossOverAppUserBundle:News:show}    

news_article_generate_pdf:
    pattern:  /news/article/generate_pdf
    defaults: { _controller: CrossOverAppUserBundle:News:generatePDFDocument}  

news_article_rss_feeds:
    pattern:  /news/article/rss_feeds
    defaults: { _controller: CrossOverAppUserBundle:News:generateRssFeeds}  
    
    
forgot_password_form:
    pattern:   /forgot_password_form
    defaults:  { _controller: CrossOverAppUserBundle:Security:forgotPasswordForm }

forgot_password_reset_form:
    pattern:   /forgot_password_reset_form/{email_auth_token}
    defaults:  { _controller: CrossOverAppUserBundle:Security:forgotPasswordResetForm }

forgot_password_update:
    pattern:   /forgot_password_update/{id}
    defaults:  { _controller: CrossOverAppUserBundle:Security:forgotPasswordUpdate }

password_reset_form:
    pattern:   /password_reset_form/{id}
    defaults:  { _controller: CrossOverAppUserBundle:Registration:passwordResetForm }

password_update:
    pattern:   /password_update/{id}
    defaults:  { _controller: CrossOverAppUserBundle:Registration:passwordUpdate }    

login:
    pattern:   /login
    defaults:  { _controller: CrossOverAppUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout    